### ISSUE TITLE
getting selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

### ISSUE THREAD

**Issue by mahatva** [MarketingPipeline/Python-Selenium-Action#3]
while running the code I am getting this error selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id

**Comment by MarketingPip** [comment]
Hey @mahatva - 

Hope you are doing well!

Tested this on my side & the workflow / template does not give this error. 
![image](https://github.com/MarketingPipeline/Python-Selenium-Action/assets/86180097/8fa83bc1-bc88-479d-a7a0-2f7a2826c8f5)

That said this issue is due to changes in your code from this current template. This stack overflow post should help you fix your problem based on the code I viewed in your profile! See [here](https://stackoverflow.com/questions/56483403/selenium-common-exceptions-webdriverexception-message-invalid-session-id-using).

Hope this helps & best of luck! 👍

If you run into any issues that have to directly with errors related to this template - feel free to ask for help / open a issue!  ✌️

**Comment by mahatva** [comment]
hy buddy,
could you please rectify error in my code?
it is very simple code..
https://github.com/mahatva/dvdvdsv/blob/main/Selenium-Template.py

**Comment by MarketingPip** [comment]
@mahatva - 

I can't say this will solve your current error in your last workflow action run [here](https://github.com/mahatva/dvdvdsv/actions/runs/5330161503/jobs/9656559827). 

But try un-commenting these - 
```
    #"--no-sandbox",
    #"--disable-dev-shm-usage",
```

Hope this helps!

ps: keep trying, playing & learning! You got this!

**Comment by mahatva** [comment]
unfortunately it didn't worked.

**Comment by MarketingPip** [comment]
Like I said @mahatva - not really a issue related directly to this repo! I would suggest trying some online forums / StackOverflow for some coding support groups to help you find the issue with your code! 

Not that I am trying to fluff off helping you - but really just not the place here to help you!
